export type Property = {
  id: string;
  title: string;
  location: string;
  city: string;
  state: string;
  country: string;
  price: number;
  beds: number;
  baths: number;
  area: number;
  type: "Villa" | "Penthouse" | "Farmhouse" | "Haveli" | "Bungalow" | "Duplex";
  image: string;
  gallery: string[];
  lat: number;
  lng: number;
  featured?: boolean;
  description: string;
  features: string[];
  possession: string;
  reraId?: string;
};

const IMG = {
  mumbai1: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=1000&fit=crop&q=80",
  mumbai2: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=1000&fit=crop&q=80",
  mumbai3: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=1000&fit=crop&q=80",
  mumbai4: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=1000&fit=crop&q=80",
  delhi1: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=1000&fit=crop&q=80",
  delhi2: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1000&fit=crop&q=80",
  delhi3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=1000&fit=crop&q=80",
  villa1: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=1000&fit=crop&q=80",
  villa2: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=1000&fit=crop&q=80",
  villa3: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=1000&fit=crop&q=80",
  goa1: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&h=1000&fit=crop&q=80",
  goa2: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=1000&fit=crop&q=80",
  haveli1: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=1000&fit=crop&q=80",
  haveli2: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=1000&fit=crop&q=80",
  luxury1: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=1000&fit=crop&q=80",
  luxury2: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=1000&fit=crop&q=80",
  penthouse1: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1000&fit=crop&q=80",
  penthouse2: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=1000&fit=crop&q=80",
  farm1: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=1000&fit=crop&q=80",
  farm2: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=1000&fit=crop&q=80",
};

const G = (primary: string, ...rest: string[]): string[] => [primary, ...rest];

export const properties: Property[] = [
  {
    id: "sea-face-mansion-bandra",
    title: "Sea Face Mansion",
    location: "Bandra West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    price: 85_00_00_000,
    beds: 5,
    baths: 6,
    area: 6200,
    type: "Penthouse",
    image: IMG.mumbai1,
    gallery: G(IMG.mumbai1, IMG.mumbai2, IMG.luxury1, IMG.penthouse1),
    lat: 19.0596,
    lng: 72.8295,
    featured: true,
    description:
      "A breathtaking sea-facing penthouse overlooking the Arabian Sea. Floor-to-ceiling glass, Italian marble flooring, private terrace with infinity pool, and uninterrupted Bandra-Worli Sea Link views.",
    features: ["Sea View", "Private Terrace Pool", "Italian Marble", "Smart Home", "Maid's Room", "3 Car Parking"],
    possession: "Ready to Move",
    reraId: "P51800034567",
  },
  {
    id: "worli-sky-residence",
    title: "Worli Sky Residence",
    location: "Worli Sea Face, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    price: 120_00_00_000,
    beds: 6,
    baths: 7,
    area: 8500,
    type: "Penthouse",
    image: IMG.mumbai2,
    gallery: G(IMG.mumbai2, IMG.luxury1, IMG.mumbai1, IMG.penthouse2),
    lat: 19.0176,
    lng: 72.8147,
    featured: true,
    description:
      "A triplex penthouse on the 65th floor with 360-degree views of the Arabian Sea and Mumbai skyline. Private elevator, home theatre, temperature-controlled wine cellar, and a rooftop helipad.",
    features: ["Helipad Access", "Private Elevator", "Home Theatre", "Wine Cellar", "Rooftop Garden", "Concierge Service"],
    possession: "Ready to Move",
    reraId: "P51800045890",
  },
  {
    id: "juhu-beach-villa",
    title: "Juhu Beach Villa",
    location: "Juhu Beach Road, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    price: 65_00_00_000,
    beds: 5,
    baths: 5,
    area: 5800,
    type: "Villa",
    image: IMG.mumbai3,
    gallery: G(IMG.mumbai3, IMG.villa1, IMG.mumbai1, IMG.luxury2),
    lat: 19.0883,
    lng: 72.8264,
    description:
      "A heritage bungalow steps from Juhu Beach. Lush tropical gardens, art deco interiors, private pool, and a meditation pavilion. Once home to a legendary Bollywood filmmaker.",
    features: ["Beach Access", "Private Pool", "Art Deco Interiors", "Meditation Room", "Tropical Garden", "Staff Quarters"],
    possession: "Ready to Move",
  },
  {
    id: "altamount-road-duplex",
    title: "The Altamount Duplex",
    location: "Altamount Road, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    price: 150_00_00_000,
    beds: 7,
    baths: 8,
    area: 11000,
    type: "Duplex",
    image: IMG.mumbai4,
    gallery: G(IMG.mumbai4, IMG.luxury1, IMG.mumbai2, IMG.penthouse1),
    lat: 18.9697,
    lng: 72.8094,
    featured: true,
    description:
      "India's most prestigious address. A duplex residence on Altamount Road with panoramic Marine Drive views. Bespoke interiors by a Milanese designer, private gym, and a curated art gallery.",
    features: ["Marine Drive View", "Bespoke Interiors", "Private Gym", "Art Gallery", "Temperature-controlled Pool", "Valet Parking"],
    possession: "Ready to Move",
    reraId: "P51800067234",
  },
  {
    id: "lutyens-bungalow",
    title: "Lutyens Heritage Bungalow",
    location: "Lutyens Delhi, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    price: 135_00_00_000,
    beds: 8,
    baths: 9,
    area: 12000,
    type: "Bungalow",
    image: IMG.delhi1,
    gallery: G(IMG.delhi1, IMG.delhi2, IMG.luxury1, IMG.haveli1),
    lat: 28.6139,
    lng: 77.209,
    featured: true,
    description:
      "A rare Lutyens-era bungalow in the heart of Lutyens Delhi. Spread over 2 acres with century-old trees, formal Mughal gardens, a private library, and original art deco detailing preserved over decades.",
    features: ["2 Acre Estate", "Mughal Gardens", "Private Library", "Heritage Architecture", "Servant Quarters", "10 Car Garage"],
    possession: "Ready to Move",
  },
  {
    id: "golf-links-mansion",
    title: "Golf Links Mansion",
    location: "Golf Links, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    price: 95_00_00_000,
    beds: 6,
    baths: 7,
    area: 8800,
    type: "Bungalow",
    image: IMG.delhi2,
    gallery: G(IMG.delhi2, IMG.delhi3, IMG.luxury1, IMG.villa1),
    lat: 28.5921,
    lng: 77.2285,
    description:
      "A contemporary masterpiece overlooking Delhi Golf Club. Open-plan living, floor-to-ceiling glass, a 25-meter lap pool, and a rooftop entertainment deck with panoramic city views.",
    features: ["Golf Course View", "Lap Pool", "Rooftop Deck", "Home Automation", "Wine Room", "Chef's Kitchen"],
    possession: "Ready to Move",
  },
  {
    id: "dlf-camellias-gurgaon",
    title: "The Camellias Penthouse",
    location: "DLF Camellias, Gurugram",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    price: 75_00_00_000,
    beds: 5,
    baths: 6,
    area: 7200,
    type: "Penthouse",
    image: IMG.delhi3,
    gallery: G(IMG.delhi3, IMG.penthouse1, IMG.delhi1, IMG.luxury2),
    lat: 28.4595,
    lng: 77.0266,
    featured: true,
    description:
      "An ultra-luxury penthouse in DLF Camellias, Gurugram's most exclusive address. Private pool, golf course views, triple-height living room, and a personal concierge.",
    features: ["Golf Course View", "Private Pool", "Triple Height Ceiling", "Personal Concierge", "Spa Room", "4 Car Parking"],
    possession: "Ready to Move",
    reraId: "RC/REP/HARERA/GGM/2018/12",
  },
  {
    id: "vasant-vihar-estate",
    title: "Vasant Vihar Estate",
    location: "Vasant Vihar, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    price: 88_00_00_000,
    beds: 7,
    baths: 8,
    area: 10500,
    type: "Bungalow",
    image: IMG.luxury1,
    gallery: G(IMG.luxury1, IMG.delhi1, IMG.villa2, IMG.penthouse1),
    lat: 28.5562,
    lng: 77.1571,
    description:
      "A sprawling estate in Vasant Vihar with manicured lawns, a private temple, indoor pool, and separate guest wing. One of South Delhi's finest residences.",
    features: ["Manicured Lawns", "Private Temple", "Indoor Pool", "Guest Wing", "Home Theatre", "Staff Quarters"],
    possession: "Ready to Move",
  },
  {
    id: "indiranagar-villa",
    title: "Indiranagar Heritage Villa",
    location: "100 Feet Road, Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    price: 28_00_00_000,
    beds: 5,
    baths: 5,
    area: 4800,
    type: "Villa",
    image: IMG.villa1,
    gallery: G(IMG.villa1, IMG.villa2, IMG.luxury1, IMG.farm1),
    lat: 12.9784,
    lng: 77.6408,
    featured: true,
    description:
      "A restored colonial villa on Indiranagar's iconic 100 Feet Road. Heritage architecture meets modern luxury with a courtyard garden, home office, and rooftop terrace.",
    features: ["Heritage Architecture", "Courtyard Garden", "Home Office", "Rooftop Terrace", "Modular Kitchen", "2 Car Garage"],
    possession: "Ready to Move",
    reraId: "PRM/KA/RERA/1251/446/PR/180215",
  },
  {
    id: "whitefield-estate",
    title: "Whitefield Tech Estate",
    location: "Whitefield Main Road, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    price: 18_00_00_000,
    beds: 4,
    baths: 4,
    area: 3800,
    type: "Villa",
    image: IMG.villa2,
    gallery: G(IMG.villa2, IMG.villa3, IMG.luxury1, IMG.farm2),
    lat: 12.9698,
    lng: 77.75,
    description:
      "A modern smart villa in Bangalore's IT corridor. Fully automated home, EV charging, organic garden, and a co-working space designed for tech entrepreneurs.",
    features: ["Smart Home", "EV Charging", "Organic Garden", "Co-working Space", "Solar Panels", "Infinity Pool"],
    possession: "Ready to Move",
    reraId: "PRM/KA/RERA/1251/309/PR/190123",
  },
  {
    id: "koramangala-penthouse",
    title: "Koramangala Sky Penthouse",
    location: "80 Feet Road, Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    price: 22_00_00_000,
    beds: 4,
    baths: 5,
    area: 5200,
    type: "Penthouse",
    image: IMG.villa3,
    gallery: G(IMG.villa3, IMG.penthouse1, IMG.luxury2, IMG.villa1),
    lat: 12.9352,
    lng: 77.6245,
    description:
      "A duplex penthouse in Koramangala with panoramic city views. Private terrace garden, jacuzzi, gourmet kitchen, and direct elevator access.",
    features: ["City View", "Terrace Garden", "Jacuzzi", "Gourmet Kitchen", "Private Elevator", "Home Theatre"],
    possession: "Dec 2025",
  },
  {
    id: "goa-portuguese-villa",
    title: "Portuguese Heritage Villa",
    location: "Assagao, North Goa",
    city: "Goa",
    state: "Goa",
    country: "India",
    price: 15_00_00_000,
    beds: 6,
    baths: 6,
    area: 5500,
    type: "Villa",
    image: IMG.goa1,
    gallery: G(IMG.goa1, IMG.goa2, IMG.villa1, IMG.farm1),
    lat: 15.5937,
    lng: 73.7671,
    featured: true,
    description:
      "A 200-year-old Portuguese mansion meticulously restored with modern amenities. Private pool, spice garden, chapel, and 1 acre of lush tropical land in Assagao.",
    features: ["Heritage Property", "Private Pool", "Spice Garden", "Chapel", "Tropical Garden", "Staff Quarters"],
    possession: "Ready to Move",
  },
  {
    id: "goa-beachfront-mansion",
    title: "Candolim Beach Mansion",
    location: "Candolim Beach, North Goa",
    city: "Goa",
    state: "Goa",
    country: "India",
    price: 25_00_00_000,
    beds: 7,
    baths: 8,
    area: 7200,
    type: "Villa",
    image: IMG.goa2,
    gallery: G(IMG.goa2, IMG.goa1, IMG.luxury1, IMG.villa2),
    lat: 15.5167,
    lng: 73.7632,
    description:
      "A beachfront mansion with direct beach access. Infinity pool overlooking the Arabian Sea, private bar, outdoor cinema, and a helipad for exclusive arrivals.",
    features: ["Beach Access", "Infinity Pool", "Private Bar", "Outdoor Cinema", "Helipad", "Yacht Mooring"],
    possession: "Ready to Move",
  },
  {
    id: "goa-riverside-estate",
    title: "Mandovi Riverside Estate",
    location: "Divar Island, Goa",
    city: "Goa",
    state: "Goa",
    country: "India",
    price: 12_00_00_000,
    beds: 5,
    baths: 5,
    area: 6000,
    type: "Farmhouse",
    image: IMG.farm1,
    gallery: G(IMG.farm1, IMG.goa1, IMG.villa1, IMG.farm2),
    lat: 15.5287,
    lng: 73.8864,
    description:
      "A secluded riverside estate on Divar Island. Private jetty, organic farm, yoga pavilion, and panoramic river views. Accessible only by ferry — true island living.",
    features: ["River View", "Private Jetty", "Organic Farm", "Yoga Pavilion", "Boat House", "Bird Watching Deck"],
    possession: "Ready to Move",
  },
  {
    id: "jaipur-haveli",
    title: "Royal Haveli Jaipur",
    location: "Civil Lines, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    price: 35_00_00_000,
    beds: 10,
    baths: 10,
    area: 14000,
    type: "Haveli",
    image: IMG.haveli1,
    gallery: G(IMG.haveli1, IMG.haveli2, IMG.luxury1, IMG.villa1),
    lat: 26.9124,
    lng: 75.7873,
    featured: true,
    description:
      "A 300-year-old Rajput haveli with intricate jharokhas, courtyards, and hand-painted frescoes. Converted into a luxury residence with modern amenities while preserving its royal heritage.",
    features: ["Heritage Frescoes", "Royal Courtyards", "Jharokhas", "Private Museum", "Rooftop Restaurant", "Horse Stable"],
    possession: "Ready to Move",
  },
  {
    id: "jaipur-golf-course-villa",
    title: "Rambagh Golf Villa",
    location: "Rambagh, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    price: 18_00_00_000,
    beds: 5,
    baths: 6,
    area: 6500,
    type: "Villa",
    image: IMG.haveli2,
    gallery: G(IMG.haveli2, IMG.haveli1, IMG.villa1, IMG.luxury2),
    lat: 26.8937,
    lng: 75.8078,
    description:
      "A contemporary villa overlooking Rambagh Golf Course. Rajasthani stone architecture, private pool, zen garden, and a home spa with traditional hammam.",
    features: ["Golf Course View", "Private Pool", "Zen Garden", "Hammam Spa", "Modular Kitchen", "3 Car Garage"],
    possession: "Ready to Move",
  },
  {
    id: "banjara-hills-mansion",
    title: "Banjara Hills Mansion",
    location: "Road No. 12, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    price: 42_00_00_000,
    beds: 6,
    baths: 7,
    area: 8200,
    type: "Bungalow",
    image: IMG.luxury1,
    gallery: G(IMG.luxury1, IMG.luxury2, IMG.villa1, IMG.penthouse1),
    lat: 17.4156,
    lng: 78.4347,
    featured: true,
    description:
      "A palatial mansion in Banjara Hills with Nizami architecture. Grand durbar hall, private cinema, temperature-controlled pool, and a curated collection of Deccani art.",
    features: ["Nizami Architecture", "Durbar Hall", "Private Cinema", "Deccani Art Collection", "Indoor Pool", "Helipad"],
    possession: "Ready to Move",
    reraId: "P02200001234",
  },
  {
    id: "jubilee-hills-duplex",
    title: "Jubilee Hills Duplex",
    location: "Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    price: 28_00_00_000,
    beds: 5,
    baths: 5,
    area: 5800,
    type: "Duplex",
    image: IMG.luxury2,
    gallery: G(IMG.luxury2, IMG.penthouse1, IMG.luxury1, IMG.villa2),
    lat: 17.4319,
    lng: 78.4078,
    description:
      "A modern duplex in Jubilee Hills with Hussain Sagar lake views. Italian kitchen, home office, rooftop lounge, and a private gym.",
    features: ["Lake View", "Italian Kitchen", "Home Office", "Rooftop Lounge", "Private Gym", "Smart Home"],
    possession: "Mar 2026",
    reraId: "P02200005678",
  },
  {
    id: "koregaon-park-bungalow",
    title: "Koregaon Park Bungalow",
    location: "North Main Road, Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    price: 22_00_00_000,
    beds: 5,
    baths: 5,
    area: 5200,
    type: "Bungalow",
    image: IMG.villa1,
    gallery: G(IMG.villa1, IMG.villa2, IMG.luxury1, IMG.farm1),
    lat: 18.5362,
    lng: 73.8939,
    description:
      "A classic KP bungalow with century-old trees, private garden, and a swimming pool. Walking distance to Osho Ashram and Pune's best restaurants.",
    features: ["Heritage Trees", "Private Garden", "Swimming Pool", "Puja Room", "Servant Quarters", "2 Car Garage"],
    possession: "Ready to Move",
    reraId: "P52100012345",
  },
  {
    id: "hinjewadi-smart-villa",
    title: "Hinjewadi Smart Villa",
    location: "Hinjewadi Phase 3, Pune",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    price: 12_00_00_000,
    beds: 4,
    baths: 4,
    area: 3500,
    type: "Villa",
    image: IMG.villa2,
    gallery: G(IMG.villa2, IMG.villa3, IMG.luxury1, IMG.farm2),
    lat: 18.5913,
    lng: 73.7389,
    description:
      "A fully automated smart villa in Pune's IT hub. Voice-controlled everything, EV charging, solar panels, and a rooftop terrace with mountain views.",
    features: ["Smart Home", "EV Charging", "Solar Panels", "Rooftop Terrace", "Modular Kitchen", "Gated Community"],
    possession: "Jun 2026",
    reraId: "P52100067890",
  },
  {
    id: "boat-club-villa",
    title: "Boat Club Villa",
    location: "Boat Club Road, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    price: 38_00_00_000,
    beds: 6,
    baths: 6,
    area: 7500,
    type: "Villa",
    image: IMG.haveli1,
    gallery: G(IMG.haveli1, IMG.haveli2, IMG.villa1, IMG.luxury1),
    lat: 13.0499,
    lng: 80.2607,
    description:
      "A Chettinad-style luxury villa on Chennai's most prestigious road. Heritage Athangudi tiles, private pool, temple garden, and a traditional kolam courtyard.",
    features: ["Chettinad Architecture", "Athangudi Tiles", "Temple Garden", "Private Pool", "Kolam Courtyard", "Heritage Interiors"],
    possession: "Ready to Move",
  },
  {
    id: "ecr-beach-house",
    title: "ECR Beach House",
    location: "East Coast Road, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    price: 16_00_00_000,
    beds: 5,
    baths: 5,
    area: 4800,
    type: "Farmhouse",
    image: IMG.goa1,
    gallery: G(IMG.goa1, IMG.farm1, IMG.villa1, IMG.goa2),
    lat: 12.9165,
    lng: 80.2451,
    description:
      "A beachfront farmhouse on ECR with private beach access. Coconut grove, outdoor shower, surfing equipment, and a seafood kitchen designed for entertaining.",
    features: ["Beach Access", "Coconut Grove", "Outdoor Shower", "Surfing Setup", "Seafood Kitchen", "Bonfire Pit"],
    possession: "Ready to Move",
  },
  {
    id: "alipore-mansion",
    title: "Alipore Royal Mansion",
    location: "Alipore, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    price: 45_00_00_000,
    beds: 8,
    baths: 9,
    area: 11000,
    type: "Haveli",
    image: IMG.haveli2,
    gallery: G(IMG.haveli2, IMG.haveli1, IMG.luxury1, IMG.villa1),
    lat: 22.5335,
    lng: 88.3373,
    featured: true,
    description:
      "A Zamindari mansion in Alipore with original Bengal Renaissance architecture. Marble halls, private library, vintage car garage, and 2 acres of manicured gardens.",
    features: ["Zamindari Heritage", "Marble Halls", "Private Library", "Vintage Car Garage", "Rose Garden", "Pond"],
    possession: "Ready to Move",
  },
  {
    id: "new-town-penthouse",
    title: "New Town Penthouse",
    location: "Action Area II, New Town",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    price: 8_50_00_000,
    beds: 4,
    baths: 4,
    area: 3200,
    type: "Penthouse",
    image: IMG.penthouse1,
    gallery: G(IMG.penthouse1, IMG.penthouse2, IMG.luxury1, IMG.villa1),
    lat: 22.5804,
    lng: 88.4667,
    description:
      "A modern penthouse in Kolkata's smart city. Lake views, rooftop garden, home automation, and access to club house with Olympic-size pool.",
    features: ["Lake View", "Rooftop Garden", "Smart Home", "Club House Access", "Olympic Pool", "Gym"],
    possession: "Sep 2025",
    reraId: "HIRA/P/NOR/2018/000123",
  },
  {
    id: "lake-palace-villa",
    title: "Lake Pichola Villa",
    location: "Ambrai Ghat, Udaipur",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    price: 55_00_00_000,
    beds: 8,
    baths: 9,
    area: 12000,
    type: "Haveli",
    image: IMG.luxury2,
    gallery: G(IMG.luxury2, IMG.haveli1, IMG.villa1, IMG.luxury1),
    lat: 24.5764,
    lng: 73.6913,
    featured: true,
    description:
      "A lakeside haveli with uninterrupted views of Lake Pichola and the City Palace. Private boat dock, rooftop restaurant, and centuries-old Rajasthani craftsmanship throughout.",
    features: ["Lake View", "Private Boat Dock", "Rooftop Restaurant", "Heritage Craftsmanship", "Courtyard Fountain", "Spa"],
    possession: "Ready to Move",
  },
  {
    id: "shimla-hill-retreat",
    title: "Shimla Heritage Retreat",
    location: "Mall Road, Shimla",
    city: "Shimla",
    state: "Himachal Pradesh",
    country: "India",
    price: 18_00_00_000,
    beds: 6,
    baths: 6,
    area: 5500,
    type: "Bungalow",
    image: IMG.farm1,
    gallery: G(IMG.farm1, IMG.farm2, IMG.villa1, IMG.luxury1),
    lat: 31.1048,
    lng: 77.1734,
    description:
      "A colonial-era bungalow on Mall Road with panoramic Himalayan views. Original fireplaces, wooden interiors, apple orchard, and a private meditation room.",
    features: ["Himalayan View", "Colonial Heritage", "Fireplace", "Apple Orchard", "Meditation Room", "Wooden Interiors"],
    possession: "Ready to Move",
  },
  {
    id: "lonavala-mountain-villa",
    title: "Lonavala Mountain Villa",
    location: "Tiger Point, Lonavala",
    city: "Lonavala",
    state: "Maharashtra",
    country: "India",
    price: 9_50_00_000,
    beds: 4,
    baths: 4,
    area: 3800,
    type: "Farmhouse",
    image: IMG.farm2,
    gallery: G(IMG.farm2, IMG.farm1, IMG.villa1, IMG.goa1),
    lat: 18.7537,
    lng: 73.4068,
    description:
      "A mountain villa at Tiger Point with valley views. Infinity pool, bonfire area, organic farm, and a treehouse for weekend getaways from Mumbai and Pune.",
    features: ["Valley View", "Infinity Pool", "Bonfire Area", "Organic Farm", "Treehouse", "Rain Water Harvesting"],
    possession: "Ready to Move",
  },
  {
    id: "amritsar-heritage-haveli",
    title: "Heritage Haveli Amritsar",
    location: "Ranjit Avenue, Amritsar",
    city: "Amritsar",
    state: "Punjab",
    country: "India",
    price: 14_00_00_000,
    beds: 6,
    baths: 6,
    area: 6500,
    type: "Haveli",
    image: IMG.haveli1,
    gallery: G(IMG.haveli1, IMG.haveli2, IMG.villa1, IMG.luxury1),
    lat: 31.634,
    lng: 74.8723,
    description:
      "A Punjabi haveli with ornate interiors, private gurdwara, mango orchard, and a traditional Punjabi kitchen. Minutes from the Golden Temple.",
    features: ["Heritage Architecture", "Private Gurdwara", "Mango Orchard", "Punjabi Kitchen", "Courtyard", "Staff Quarters"],
    possession: "Ready to Move",
  },
  {
    id: "chandigarh-sector-5-villa",
    title: "Sector 5 Villa",
    location: "Sector 5, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    price: 16_00_00_000,
    beds: 5,
    baths: 5,
    area: 5000,
    type: "Villa",
    image: IMG.villa3,
    gallery: G(IMG.villa3, IMG.villa1, IMG.luxury1, IMG.farm1),
    lat: 30.7333,
    lng: 76.7794,
    description:
      "A Le Corbusier-inspired modernist villa in Chandigarh's most exclusive sector. Clean lines, open plan, private garden, and a lap pool.",
    features: ["Modernist Design", "Private Garden", "Lap Pool", "Open Plan", "Smart Home", "2 Car Garage"],
    possession: "Ready to Move",
  },
];

export const formatPrice = (n: number): string => {
  if (n >= 1_00_00_000) {
    const cr = n / 1_00_00_000;
    return `₹${cr % 1 === 0 ? cr.toFixed(0) : cr.toFixed(1)} Cr`;
  } else if (n >= 1_00_000) {
    const lac = n / 1_00_000;
    return `₹${lac % 1 === 0 ? lac.toFixed(0) : lac.toFixed(1)} Lac`;
  }
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
};

export const formatArea = (sqft: number): string => {
  return `${sqft.toLocaleString("en-IN")} sq ft`;
};
